algoritmo "semnome"
// Função :
// Autor :
// Data : 31/05/2017
// Seção de Declarações 
var
     n1, n2: INTEIRO
inicio
// Seção de Comandos
    escreva ("informe o valor A")
    leia (n1)
    escreva ("informe o valor B")
    leia (n2)

        se
        (n1>n2)
        soma:=(n1+100)
        escreva ("o valor somado a 100 é:,soma")
        senao
        soma:=(n2+100)
        escreva ("o valor somado a 100 é:,soma")
        fimse
fimalgoritmo
